baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Veteran Scrap Removal"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Up Business"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images:
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Manchester, NH 03104"

  contact:
    - "contact-us@veteranscrapremoval.com"
    - "999.555.1234"

  copyright: "Â© 2023 Veteran Scrap Removal"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/pricing"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
